In [21]:
import pandas as pd
import numpy as np
from sklearn.utils import resample

# Set seed for reproducibility
np.random.seed(42)

# Create 1000 data points
n_samples = 12
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio) # 900
n_class_1 = n_samples - n_class_0           # 100

# Generate Features (Normal Distribution)
class_0_data = pd.DataFrame({
    'feature_1': np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature_2': np.random.normal(loc=0, scale=1, size=n_class_0),
    'target': [0] * n_class_0
})

class_1_data = pd.DataFrame({
    'feature_1': np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature_2': np.random.normal(loc=2, scale=1, size=n_class_1),
    'target': [1] * n_class_1
})

# Combine into one DataFrame
df = pd.concat([class_0_data, class_1_data]).reset_index(drop=True)

print(df['target'].value_counts())
# Output: 0: 900, 1: 100

target
0    10
1     2
Name: count, dtype: int64

In [22]:
class_0_data

   feature_1  feature_2  target
0   0.496714  -0.463418       0
1  -0.138264  -0.465730       0
2   0.647689   0.241962       0
3   1.523030  -1.913280       0
4  -0.234153  -1.724918       0
5  -0.234137  -0.562288       0
6   1.579213  -1.012831       0
7   0.767435   0.314247       0
8  -0.469474  -0.908024       0
9   0.542560  -1.412304       0

In [23]:
df_majority = df[df.target == 0]
df_minority = df[df.target == 1]

In [24]:
df_majority

   feature_1  feature_2  target
0   0.496714  -0.463418       0
1  -0.138264  -0.465730       0
2   0.647689   0.241962       0
3   1.523030  -1.913280       0
4  -0.234153  -1.724918       0
5  -0.234137  -0.562288       0
6   1.579213  -1.012831       0
7   0.767435   0.314247       0
8  -0.469474  -0.908024       0
9   0.542560  -1.412304       0

## Demonstration: Upsampling

In [25]:
# Upsample Minority Class
df_minority_upsampled = resample(df_minority, 
                                 replace=True,     # Sample with replacement
                                 n_samples=len(df_majority), # To match 900
                                 random_state=42)

# Combine back
df_upsampled = pd.concat([df_majority, df_minority_upsampled])

print(df_upsampled['target'].value_counts())
# Output: 0: 900, 1: 900

target
0    10
1    10
Name: count, dtype: int64

In [26]:
df_minority_upsampled

    feature_1  feature_2  target
10   3.465649   2.067528       1
11   1.774224   0.575252       1
10   3.465649   2.067528       1
10   3.465649   2.067528       1
10   3.465649   2.067528       1
11   1.774224   0.575252       1
10   3.465649   2.067528       1
10   3.465649   2.067528       1
10   3.465649   2.067528       1
11   1.774224   0.575252       1

## Demonstartion: Downsample

In [27]:
# Downsample Majority Class
df_majority_downsampled = resample(df_majority, 
                                   replace=False,    # No replacement needed
                                   n_samples=len(df_minority), # To match 100
                                   random_state=42)

# Combine back
df_downsampled = pd.concat([df_minority, df_majority_downsampled])

print(df_downsampled['target'].value_counts())
# Output: 1: 100, 0: 100

target
1    2
0    2
Name: count, dtype: int64

In [28]:
df_downsampled

    feature_1  feature_2  target
10   3.465649   2.067528       1
11   1.774224   0.575252       1
8   -0.469474  -0.908024       0
1   -0.138264  -0.465730       0